name: Build pmOS begonia

on:
  workflow_dispatch:
    inputs:
      ui:
        description: UI
        required: true
        default: console
        type: choice
        options:
          - console
          - phosh
      fde:
        description: FDE
        required: true
        default: "false"
        type: choice
        options:
          - "false"
          - "true"
      extra:
        description: Extra MB
        required: true
        default: "1024"
      cross:
        description: Cross
        required: true
        default: "true"
        type: choice
        options:
          - "true"
          - "false"
      branch:
        description: Branch
        required: true
        default: main
        type: choice
        options:
          - main
          - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo hi